package com.example.gameon.classes

import android.os.Parcelable
import java.util.Date
import kotlinx.parcelize.Parcelize

@Parcelize
data class User(
    val discord_id: String,
    val username: String,
    val email: String,
    val created_at: Date? = null, //autogenerated on server side
    val banned: Boolean = false,
    val avatar: String? = null,
    val preference_id: Int? = null,
    val preferences: Preferences? = null
) : Parcelable
